### PR TITLE
[WASI] http child resources

### PR DESCRIPTION
**Pull request by pavelsavara**
to match https://github.com/dotnet/runtime/pull/107096

### CODE REVIEW

**Comment by pavelsavara** [comment]
Test case:

```ps1

.\dotnet.cmd build -bl:test.binlog /t:BuildNativeAot /p:TestBuildMode=nativeaot /p:TargetArchitecture=wasm /p:TargetOS=wasi /p:LibrariesConfiguration=Debug -c Debug src\tests\nativeaot\SmokeTests\http-p2\Wasip2.Http.Console.Sample.csproj

wasmtime run --wasi http c:\Dev\runtimelab\artifacts\tests\coreclr\wasi.wasm.Debug\nativeaot\SmokeTests\http-p2\Wasip2.Http.Console.Sample\native\Wasip2.Http.Console.Sample.wasm

```

**Comment by dicej** [comment]
FYI, I'm just now getting around to testing this locally, and getting a trap due to open child resources here:
```
    0: 0xd474ae - .tmpcKxDbB!System_Net_Http_WasiHttpWorld_wit_imports_wasi_io_v0_2_1_IStreams_InputStream__wasmImportResourceDrop
    1: 0x2c2c68 - .tmpcKxDbB!System_Net_Http_WasiHttpWorld_wit_imports_wasi_io_v0_2_1_IStreams_InputStream__Dispose_0
    2: 0xd3e1b4 - .tmpcKxDbB!System_Net_Http_WasiHttpWorld_wit_imports_wasi_io_v0_2_1_IStreams_InputStream__Dispose
    3: 0x2a8130 - .tmpcKxDbB!System_Net_Http_System_Net_Http_WasiInputStream__Close
    4: 0xc0d677 - .tmpcKxDbB!S_P_CoreLib_System_IO_Stream__Dispose
    5: 0xbb829e - .tmpcKxDbB!System_Net_Http_System_IO_DelegatingStream__Dispose
    6: 0x195aef - .tmpcKxDbB!S_P_CoreLib_System_IO_Stream__Close
    7: 0xc0d677 - .tmpcKxDbB!S_P_CoreLib_System_IO_Stream__Dispose
```

I'm out of time for today, but I'll dig into it tomorrow.

**Comment by dicej** [comment]
Presumably the above is due to a child `pollable`, since that's the only kind of child an `input-stream` can have.

**Comment by pavelsavara** [comment]
Sleeping on it fixed resolved the issue, like usual 😉

**Comment by dicej** [comment]
I've cherry-picked your changes in and fixed the conflicts; so I'll close this.  Thanks!

**Comment by pavelsavara** [comment]
I processed your feedback on the other PR, it will eventually flow ...

**Pull request closed without merging**
